export type FolderLocation =
  | "youtube"
  | "downloaded"
  | "itunes"
  | "music"
  | "downloads"
  | "playlists"
  | "formatted"
  | "broken"
  | "djMusic"
  | "rename"
  | "transfer"
  | "backup"
  | "djPlaylists"
  | "djPlaylistImport";
